//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCentreFollowUps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FCProjectRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FCProjectRequest()
        {
            this.PaymentDetails = new HashSet<PaymentDetail>();
        }
    
        public int RequestID { get; set; }
        public Nullable<int> SupervisorID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> FieldCoordinatorID { get; set; }
        public Nullable<int> NumberOfInterviews { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> TotalDue { get; set; }
        public string Comments { get; set; }
        public System.DateTime DateRequested { get; set; }
        public string AddedBy { get; set; }
    
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
        public virtual Supervisor Supervisor { get; set; }
    }
}
