//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCentreFollowUps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public int PaymentID { get; set; }
        public Nullable<int> RequestID { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    
        public virtual FCProjectRequest FCProjectRequest { get; set; }
    }
}
